const PALETTE = [
    // default
    { hex: '#000000', name: 'Black' },
    { hex: '#3c3c3c', name: 'Dark Gray' },
    { hex: '#787878', name: 'Gray' },
    { hex: '#d2d2d2', name: 'Light Gray' },
    { hex: '#ffffff', name: 'White' },
    { hex: '#600018', name: 'Deep Red' },
    { hex: '#ed1c24', name: 'Red' },
    { hex: '#ff7f27', name: 'Orange' },
    { hex: '#f6aa09', name: 'Gold' },
    { hex: '#f9dd3b', name: 'Yellow' },
    { hex: '#fffabc', name: 'Light Yellow' },
    { hex: '#0eb968', name: 'Dark Green' },
    { hex: '#13e67b', name: 'Green' },
    { hex: '#87ff5e', name: 'Light Green' },
    { hex: '#0c816e', name: 'Dark Teal' },
    { hex: '#10aea6', name: 'Teal' },
    { hex: '#13e1be', name: 'Light Teal' },
    { hex: '#28509e', name: 'Dark Blue' },
    { hex: '#4093e4', name: 'Blue' },
    { hex: '#60f7f2', name: 'Cyan' },
    { hex: '#6b50f6', name: 'Indigo' },
    { hex: '#99b1fb', name: 'Light Indigo' },
    { hex: '#780c99', name: 'Dark Purple' },
    { hex: '#aa38b9', name: 'Purple' },
    { hex: '#e09ff9', name: 'Light Purple' },
    { hex: '#cb007a', name: 'Dark Pink' },
    { hex: '#ec1f80', name: 'Pink' },
    { hex: '#f38da9', name: 'Light Pink' },
    { hex: '#684634', name: 'Dark Brown' },
    { hex: '#95682a', name: 'Brown' },
    { hex: '#f8b277', name: 'Beige' },

    // option
    { hex: '#aaaaaa', name: 'Medium Gray' },
    { hex: '#a50e1e', name: 'Dark Red' },
    { hex: '#fa8072', name: 'Light Red' },
    { hex: '#e45c1a', name: 'Dark Orange' },
    { hex: '#d6b594', name: 'Light Tan' },
    { hex: '#9c8431', name: 'Dark Goldenrod' },
    { hex: '#c5ad31', name: 'Goldenrod' },
    { hex: '#e8d45f', name: 'Light Goldenrod' },
    { hex: '#4a6b3a', name: 'Dark Olive' },
    { hex: '#5a944a', name: 'Olive' },
    { hex: '#84c573', name: 'Light Olive' },
    { hex: '#0f799f', name: 'Dark Cyan' },
    { hex: '#bbfaf2', name: 'Light Cyan' },
    { hex: '#7dc7ff', name: 'Light Blue' },
    { hex: '#4d31b8', name: 'Dark Indigo' },
    { hex: '#4a4284', name: 'Dark Slate Blue' },
    { hex: '#7a71c4', name: 'Slate Blue' },
    { hex: '#b5aef1', name: 'Light Slate Blue' },
    { hex: '#dba463', name: 'Light Brown' },
    { hex: '#d18051', name: 'Dark Beige' },
    { hex: '#ffc5a5', name: 'Light Beige' },
    { hex: '#9b5249', name: 'Dark Peach' },
    { hex: '#d18078', name: 'Peach' },
    { hex: '#fab6a4', name: 'Light Peach' },
    { hex: '#7b6352', name: 'Dark Tan' },
    { hex: '#9c846b', name: 'Tan' },
    { hex: '#333941', name: 'Dark Slate' },
    { hex: '#6d758d', name: 'Slate' },
    { hex: '#b3b9d1', name: 'Light Slate' }
]

// パレットを分割
export const DEFAULT_COLORS = PALETTE.slice(0, 31)
export const SELECTABLE_COLORS = PALETTE.slice(31)

export const COLOR_NAME_MAP = Object.fromEntries(PALETTE.map(c => [c.hex, c.name]))
