import type { Metadata } from "next"
import { DotGothic16 } from "next/font/google"
import { ThemeProvider } from "@/lib/theme_provider"
import "./globals.css"

const dotGothic = DotGothic16({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dot-gothic-16",
})

export const metadata: Metadata = {
  title: "Wplace Image Conversion",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${dotGothic.variable} antialiased`}
        style={{
          backgroundColor: "var(--background-main)",
          color: "var(--text-main)",
        }}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
