import type { Metadata } from "next"
import { DotGothic16 } from "next/font/google"
import { headers } from "next/headers"
import "./globals.css"

const dotGothic = DotGothic16({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dot-gothic-16",
})

export const metadata: Metadata = {
  title: "Wplace Image Conversion",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const userAgent = (await headers()).get("user-agent") || ""
  const isMobile = /iPhone|iPad|iPod|Android/i.test(userAgent)

  if (isMobile) {
    return (
      <html lang="ja">
        <body className={`${dotGothic.variable} flex h-dvh w-full items-center justify-center bg-gray-100 antialiased`}>
          <div className="text-center">
            <p>パソコンでアクセスしてください</p>
          </div>
        </body>
      </html>
    )
  }

  return (
    <html lang="ja">
      <body className={`${dotGothic.variable} antialiased`}>{children}</body>
    </html>
  )
}
